name: ${modName}
author: ${modAuthor}
version: ${version}
website: ${githubUrl}

main: dev.entirety.enoughslime.bukkit.EnoughSlime
depend: [Slimefun]

api-version: ${minecraftApiVersion}

commands:
  enoughslime:
    aliases: es
